# Generated by Django 3.0.5 on 2020-04-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200420_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(default='I am using TalkingMind', max_length=150),
        ),
    ]
