# Generated by Django 2.1.3 on 2020-04-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200425_1934'),
        ('blog', '0003_auto_20200427_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ArticleCategory'),
        ),
    ]
