# Generated by Django 3.0.8 on 2020-07-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprivacysetting',
            name='unrecognized_login_alert',
            field=models.CharField(default='enabled', max_length=20),
        ),
    ]
